service: realty-bot
frameworkVersion: '3'
configValidationMode: error
useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x
    region: ${env:AWS_REGION}
    versionFunctions: false
    stage: dev
    environment:
        TG_BOT_TOKEN: ${env:TG_BOT_TOKEN}
        YA_TOKEN: ${env:YA_TOKEN}
        ADMIN_CHAT_ID: ${env:ADMIN_CHAT_ID}
        APP_ENV: ${env:APP_ENV, self:provider.stage}
        AWS_PROJECT_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
        AWS_PROJECT_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
        AWS_PROJECT_REGION: ${env:AWS_REGION}

package:
    patterns:
        - '!src/**'
        - '!tests/**'
        - '!.dynamodb/**'
        - '!.github/**'
        - '!.idea/**'
        - '!config/**'
        - '!jest.config.ts'
        - '!*.json'
        - '!readme.md'

plugins:
    - serverless-dynamodb-local
    - serverless-offline
    - serverless-express

resources:
    - ${file(config/resources.yml)}

functions:
    ${file(config/functions.yml)}

custom:
    dynamodb:
        stages:
            - offline
        start:
            migrate: true