import Location from "../enums/location";

export default {
    [Location.BUDAPEST]: {
        newly: 'Newly',
        pets: 'With pets',
        condi: 'Air conditioning',
        furnished: 'Furnished',
        balcony: 'Balcony',
        "room-2": 'Min. 2 rooms',
        "room-3": 'Min. 3 rooms',
        "room-4": 'Min. 4 rooms',
        "price-150": 'Min 150th',
        "price-200": 'Min 200th',
        "price-250": 'Min 250th',
        "price-300": 'Min 300th',
        "max-250": 'Max 250th',
        "max-350": 'Max 350th',
        "max-400": 'Max 400th',
        "max-500": 'Max 500th',
    },
    [Location.BELGRADE]: {
        newly: 'Newly',
        pets: 'With pets',
        condi: 'Air conditioning',
        furnished: 'Furnished',
        balcony: 'Balcony',
        "room-2": 'Min. 2 rooms',
        "room-3": 'Min. 3 rooms',
        "room-4": 'Min. 4 rooms',
        "price-450": 'Min 450€',
        "price-500": 'Min 500€',
        "price-550": 'Min 550€',
        "price-650": 'Min 650€',
        "max-600": 'Max 600€',
        "max-700": 'Max 700€',
        "max-800": 'Max 800€',
        "max-1000": 'Max 1000€',
    }
}