Resources:
    settings:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: settings
            AttributeDefinitions:
                -   AttributeName: chatId
                    AttributeType: N
                -   AttributeName: lastUsage
                    AttributeType: N
            KeySchema:
                -   AttributeName: chatId
                    KeyType: HASH
                -   AttributeName: lastUsage
                    KeyType: RANGE
            BillingMode: PROVISIONED
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1