Resources:
    settings:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: settings
            AttributeDefinitions:
                -   AttributeName: chatId
                    AttributeType: N
            KeySchema:
                -   AttributeName: chatId
                    KeyType: HASH
            BillingMode: PROVISIONED
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1